name: "classifier_us8k_ast"
backend: "onnxruntime"
platform: "onnxruntime_onnx"
max_batch_size: 8

input [
  {
    name: "input_values"
    data_type: TYPE_FP32
    dims: [ 1024, 128 ]
  }
]

output [
  {
    name: "class_logits"
    data_type: TYPE_FP32
    dims: [ 10 ]
  }
]

instance_group [
  { count: 1, kind: KIND_CPU }
]
