name: "ast_feature_extractor"
backend: "python"
max_batch_size: 0

input [
  {
    name: "mono_audio"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "sample_rate"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]

output [
  {
    name: "input_values"
    data_type: TYPE_FP32
    dims: [ 1, 1024, 128 ]
  }
]

instance_group [
  { count: 1, kind: KIND_CPU }
]

parameters [
  { key: "TARGET_SR", value: { string_value: "16000" } },
  { key: "MAX_LENGTH", value: { string_value: "1024" } },
  { key: "NUM_MEL_BINS", value: { string_value: "128" } },
  { key: "MEAN", value: { string_value: "-4.2677393" } },
  { key: "STD", value: { string_value: "4.5689974" } }
]
