FROM nvcr.io/nvidia/tritonserver:24.08-py3

RUN apt-get update && \
    apt-get install -y --no-install-recommends libsndfile1 && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
      numpy==1.26.4 \
      scipy==1.13.1 \
      librosa==0.10.2 \
      soundfile==0.12.1 \
      numba==0.60.0

EXPOSE 8000 8001 8002
